<div class = "d-flex justify-content-center">
    <table>
        <tr>
            <td><button class="btn btn-secondary" disabled="disabled" value="1">1</button></td>
            <td><button class="btn btn-secondary" disabled="disabled" value="2">2</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="3">3</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="4">4</button></td>
        </tr>
         <tr>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="5">5</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="6">6</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="7">7</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="8">8</button></td>
        </tr>
        <tr>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="9">9</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="10">10</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="11">11</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="12">12</button></td>
        </tr>
        <tr>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="13">13</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="14">14</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="15">15</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="16">16</button></td>
        </tr>
        <tr>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="17">17</button></td>
            <td><button class="btn btn-success" onClick="saveNum(event)" value="18">18</button></td>
        </tr>
    </table>
</div>
<h6 class = "text-center"> Has seleccionado el numero: </h6>
<p class = "text-center" id= "numeroSeleccionado"> </p>